openapi: 3.0.0
info:
  title: Example API
  version: "1.1"

paths:
  /users:
    get:
      summary: Get users list   # cambiado
      responses:
        "200":
          description: OK
        "404":
          description: Not found

  /providers:
    get:
      summary: Get providers
      responses:
        "200":
          description: OK

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        full_name:         # cambiado name → full_name
          type: string

    Status:               # nuevo schema
      type: object
      properties:
        uptime:
          type: number
