openapi: 3.0.0
info:
  title: Example API
  version: "1.0"

paths:
  /users:
    get:
      summary: Get users
      responses:
        "200":
          description: OK

  /zones:
    get:
      summary: Get zones
      responses:
        "200":
          description: OK

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string

    Zone:
      type: object
      properties:
        id:
          type: string
        region:
          type: string
